apiversion: apps/v1
kind: Deployment
metadata:
  node: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  templates:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: appserver
        image: rohanrauthan/app:latest
        ports:
        - containerPort: 3000

----

apiVersion: v1
kind: Service
metadata: 
  name: app-service
spec: 
  selector:
    app: app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110