apiversion: apps/v1
kind: Deployment
metadata:
  node: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  templates:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: appserver
        image: okteto/app:latest
        ports:
        - containerPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - image: okteto.dev/app:latest
        name: app-deployment

---

apiVersion: v1
kind: Service
metadata:
  name: app-deployment
spec:
  type: ClusterIP
  ports:
  - name: "app-deployment"
    port: 8080
  selector:
    app: app-deployment

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-deployment
  annotations:
    dev.okteto.com/generate-host: app-deployment
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: app-deployment
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
